### ISSUE TITLE
Problem with buttons

### ISSUE THREAD

**Issue by Nukecraft5419** [enjarai/recursive-resources#29]
Is it possible to have Coherence between versions 1.18.2, 1.19.4, 1.20.1? We at LifeMC Studios have noticed that when using your mod on these 3 versions, the keys are different, like in 1.18.2 they are all there, then in 1.19.4 two keys are already removed, and then in 1.19.4 two more keys are removed.

**Comment by enjarai** [comment]
What exactly do you mean by keys being different/removed?

Also, please dont put your entire issue in the title. The description exists for a reason.

**Comment by Nukecraft5419** [comment]
I apologise for the title and description I have solved it, in practice in our LifeMC modpack in the 3 versions the buttons that Recursive Resources adds are different in practice there are not all those shown in each version the buttons are missing

**Comment by enjarai** [comment]
You're probably referring to the sort buttons in 1.18 -> 1.19 and the "enable/disable all" buttons in 1.19 -> 1.20. The former were removed due to internal code changes making them impractical to maintain. Meanwhile the latter weren't removed, but integrated into the titles of the two sections to clear up clutter.

Point being, the mod has significantly improved and evolved internally in the time between 1.18 and 1.20, since about one and a half years have passed between those releases.

Your main question though is if I can backport newer behaviour to older game versions. This is not something I make a habit of doing, as its very boring and time-consuming work with little tangible benefit. A perfectly functional mod version already exists for that game version after all.

If you think it's worth the time though, it'd be great if you could PR some backports. It's not difficult to do, just a bit of a hassle.

**Comment by Nukecraft5419** [comment]
At the moment I'm still not that familiar with mods, but I can develop plugins perfectly well, and this is something I need to improve, for keys placed in titles in what sense if it is possible to have which screen to understand better
